// 全站内容数据源：资源、文章、产品和联系方式统一从这里维护。
// 后续新增卡片时，先更新本文件，再让页面渲染和搜索索引复用同一份数据。
window.CONTROLROOKIE_SITE_DATA = {
  resources: [
    {
      id: "source-code",
      type: { zh: "01 · 源代码", en: "01 · Source" },
      title: { zh: "CODESYS 示例工程", en: "CODESYS Examples" },
      copy: {
        zh: "控制逻辑、通信、状态机和工程模板源码。",
        en: "Control logic, communication, state machines, and project templates.",
      },
      status: { zh: "分批整理", en: "Curating" },
      access: { zh: "后续受控下载", en: "Controlled download later" },
      format: { zh: "工程包 / ST / 说明", en: "Project package / ST / notes" },
      detail: {
        zh: "适合想直接看工程结构、状态机、通信封装和模板写法的自动化工程师。当前先作为资源目录入口，真实源码包后续按受控下载和客户转化流程开放。",
        en: "For automation engineers who want project structure, state machines, communication wrappers, and template code. Real packages will later be delivered through controlled download flows.",
      },
      bullets: {
        zh: ["CODESYS / SmartControl 工程结构", "状态机与通信逻辑示例", "后续与 MQTT 源码文章互链"],
        en: ["CODESYS / SmartControl project structure", "State machine and communication logic examples", "Future cross-links with MQTT source articles"],
      },
      related: [{ zh: "查看 MQTT 文章系列", en: "Open MQTT article series", href: "#articles-mqtt" }],
      aliases: "源码 示例工程 ST 工程包 下载",
      keywords: "PLC CODESYS source code example project control logic state machine ST engineering package download",
      href: "#works-source-code",
    },
    {
      id: "plc-library",
      type: { zh: "02 · 库文件", en: "02 · Library" },
      title: { zh: "PLC Library", en: "PLC Library" },
      copy: {
        zh: "可复用功能块、通信封装和工程基础库。",
        en: "Reusable function blocks, communication wrappers, and base libraries.",
      },
      status: { zh: "规划中", en: "Planned" },
      access: { zh: "按版本开放", en: "Versioned access" },
      format: { zh: "库文件 / 功能块", en: "Library / function blocks" },
      detail: {
        zh: "用于沉淀可复用功能块、通信封装和工程基础库。后续会按版本、适用平台和依赖关系拆分，避免把库文件变成一堆不可维护的压缩包。",
        en: "Reusable function blocks, communication wrappers, and base libraries. Future releases will be organized by version, platform, and dependency boundaries.",
      },
      bullets: {
        zh: ["功能块边界和调用约定", "通信封装与基础工具", "版本、平台和依赖说明"],
        en: ["Function block boundaries and call contracts", "Communication wrappers and base tools", "Version, platform, and dependency notes"],
      },
      related: [{ zh: "联系获取试用范围", en: "Discuss trial scope", href: "#contact" }],
      aliases: "库 功能块 FB library",
      keywords: "PLC library function block communication wrapper FB",
      href: "#works-plc-library",
    },
    {
      id: "engineering-standards",
      type: { zh: "03 · 标准", en: "03 · Standard" },
      title: { zh: "工程标准", en: "Engineering Standards" },
      copy: {
        zh: "命名、状态机、交付、测试和文档规范。",
        en: "Naming, state machines, delivery, testing, and documentation rules.",
      },
      status: { zh: "持续沉淀", en: "Ongoing" },
      access: { zh: "部分公开", en: "Partly public" },
      format: { zh: "规范 / 清单 / 模板", en: "Standards / checklists / templates" },
      detail: {
        zh: "覆盖命名、状态机、交付、测试和文档规范。目标不是写漂亮制度，而是让团队交付时少靠记忆和口头提醒。",
        en: "Naming, state machines, delivery, testing, and documentation standards. The goal is fewer memory-based and verbal-only engineering practices.",
      },
      bullets: {
        zh: ["命名与目录约定", "交付和测试清单", "文档模板与评审规则"],
        en: ["Naming and folder conventions", "Delivery and test checklists", "Documentation templates and review rules"],
      },
      related: [{ zh: "查看工程效率产品", en: "Open engineering tool", href: "#products-syncbridge" }],
      aliases: "规范 标准 checklist 交付 测试",
      keywords: "standard naming state machine test documentation checklist delivery",
      href: "#works-engineering-standards",
    },
    {
      id: "project-scaffold",
      type: { zh: "04 · 模板", en: "04 · Template" },
      title: { zh: "项目脚手架", en: "Project Scaffold" },
      copy: {
        zh: "工程初始化、目录结构、清单和验证流程。",
        en: "Initialization, folder structure, checklists, and validation workflows.",
      },
      status: { zh: "设计中", en: "Designing" },
      access: { zh: "后续开放", en: "Later release" },
      format: { zh: "目录结构 / 清单 / 脚本", en: "Folders / checklists / scripts" },
      detail: {
        zh: "把工程初始化、目录结构、清单和验证流程前置，减少每个项目从空白目录开始造轮子的时间。",
        en: "Moves initialization, folder structure, checklists, and validation forward so projects do not start from an empty directory each time.",
      },
      bullets: {
        zh: ["工程目录和命名骨架", "发布前检查清单", "静态验证和生成脚本入口"],
        en: ["Project folder and naming skeleton", "Pre-release checklist", "Static validation and generation scripts"],
      },
      related: [{ zh: "联系讨论适用项目", en: "Discuss project fit", href: "#contact" }],
      aliases: "脚手架 模板 scaffold 初始化",
      keywords: "template scaffold checklist validation workflow initialization",
      href: "#works-project-scaffold",
    },
    {
      id: "mqtt-resources",
      type: { zh: "05 · 协议", en: "05 · Protocol" },
      title: { zh: "MQTT 资料", en: "MQTT Resources" },
      copy: {
        zh: "服务器、客户端、主题设计和排障资料。",
        en: "Server, client, topic design, and troubleshooting references.",
      },
      status: { zh: "已关联文章", en: "Linked articles" },
      access: { zh: "文章优先公开", en: "Articles first" },
      format: { zh: "教程 / 图 / 源码说明", en: "Tutorials / diagrams / source notes" },
      detail: {
        zh: "围绕 MQTT Client、Broker、主题设计和排障资料展开。当前官网已经发布 MQTT Client 与 Broker 双系列文章，资料入口优先和文章互链。",
        en: "Covers MQTT Client, Broker, topic design, and troubleshooting. The website already publishes both Client and Broker article series.",
      },
      bullets: {
        zh: ["Client 与 Broker 双系列", "主题、QoS、KeepAlive 和 Retain", "现场排障与源码说明"],
        en: ["Client and Broker series", "Topic, QoS, KeepAlive, and Retain", "Troubleshooting and source notes"],
      },
      related: [{ zh: "进入 CodeSys MQTT 系列", en: "Open CodeSys MQTT series", href: "#articles-mqtt" }],
      aliases: "MQTT Client Broker 协议 通信",
      keywords: "MQTT broker server client topic troubleshooting protocol communication",
      href: "#works-mqtt-resources",
    },
    {
      id: "automation-scripts",
      type: { zh: "06 · 脚本", en: "06 · Script" },
      title: { zh: "自动化脚本", en: "Automation Scripts" },
      copy: {
        zh: "面向工程效率的批处理、检查和生成工具。",
        en: "Batch, checking, and generation tools for engineering efficiency.",
      },
      status: { zh: "内部使用中", en: "Internal use" },
      access: { zh: "择机开放", en: "Selective release" },
      format: { zh: "脚本 / 检查器 / 生成器", en: "Scripts / checkers / generators" },
      detail: {
        zh: "面向工程效率的批处理、检查和生成工具。后续只开放能稳定复用、不会误伤工程文件的脚本。",
        en: "Batch, checking, and generation tools for engineering efficiency. Future releases will prioritize stable tools that do not risk project files.",
      },
      bullets: {
        zh: ["批处理和格式检查", "文章/资源生成辅助", "工程发布前自动检查"],
        en: ["Batch processing and formatting checks", "Article/resource generation helpers", "Pre-release project checks"],
      },
      related: [{ zh: "查看技术文章", en: "Open articles", href: "#articles" }],
      aliases: "脚本 自动化 批处理 检查 生成",
      keywords: "automation scripts batch check generator engineering efficiency",
      href: "#works-automation-scripts",
    },
    {
      id: "llm-workflows",
      type: { zh: "07 · AI", en: "07 · AI" },
      title: { zh: "LLM 工作流", en: "LLM Workflows" },
      copy: {
        zh: "提示词、技能、Agent 和自动化协作规则。",
        en: "Prompts, skills, agents, and automation collaboration rules.",
      },
      status: { zh: "持续迭代", en: "Iterating" },
      access: { zh: "按场景开放", en: "Scenario-based" },
      format: { zh: "提示词 / 技能 / Agent 规则", en: "Prompts / skills / agent rules" },
      detail: {
        zh: "沉淀提示词、技能、Agent 和自动化协作规则。重点不是炫技，而是让 AI 真正接得住控制工程项目上下文。",
        en: "Prompts, skills, agents, and automation collaboration rules. The focus is making AI handle control-engineering context instead of showing tricks.",
      },
      bullets: {
        zh: ["项目规则和上下文同步", "技能与 Agent 协作方式", "AI 工程效率工作流"],
        en: ["Project rules and context sync", "Skill and agent collaboration", "AI engineering efficiency workflow"],
      },
      related: [{ zh: "查看工程效率产品", en: "Open engineering tool", href: "#products-syncbridge" }],
      aliases: "AI LLM Agent 提示词 工作流 同步器",
      keywords: "LLM prompt skill agent workflow AI automation synchronizer",
      href: "#works-llm-workflows",
    },
    {
      id: "engineering-library",
      type: { zh: "08 · 资料", en: "08 · Reference" },
      title: { zh: "工程资料库", en: "Engineering Library" },
      copy: {
        zh: "手册、笔记、复盘和关键技术路线图。",
        en: "Manuals, notes, reviews, and technical roadmaps.",
      },
      status: { zh: "整理中", en: "Curating" },
      access: { zh: "后续分级开放", en: "Tiered access later" },
      format: { zh: "手册 / 笔记 / 复盘", en: "Manuals / notes / reviews" },
      detail: {
        zh: "手册、笔记、复盘和关键技术路线图的长期入口。资料会按公开、留资、客户授权和付费等条件分级开放。",
        en: "Long-term entry for manuals, notes, reviews, and technical roadmaps. Access will be tiered by public, lead, customer, and paid conditions.",
      },
      bullets: {
        zh: ["工程手册和关键笔记", "项目复盘和路线图", "后续受控下载系统承接"],
        en: ["Engineering manuals and key notes", "Project reviews and roadmaps", "Future controlled-download delivery"],
      },
      related: [{ zh: "联系获取资料范围", en: "Discuss reference scope", href: "#contact" }],
      aliases: "资料 手册 笔记 复盘 roadmap",
      keywords: "manual note review roadmap engineering reference controlled download",
      href: "#works-engineering-library",
    },
  ],
  articles: window.CONTROLROOKIE_ARTICLES || [
    {
      id: "mqtt-client-open-source-codesys-layer",
      type: { zh: "文章", en: "Article" },
      title: {
        zh: "官方 MQTT 库要花钱？我为什么自己开源了一套 CODESYS MQTT 客户端",
        en: "Why I Built an Open Source CODESYS MQTT Client",
      },
      copy: {
        zh: "MQTT Client 系列第一篇：为什么要做开源客户端、MQTT 在哪一层、以及 NBS TCP 与 MQTT 的工程关系。",
        en: "The first MQTT Client article: why this open source client exists, where MQTT sits, and how NBS TCP carries MQTT in CODESYS.",
      },
      href: "articles/mqtt-client-open-source-codesys-layer/index.html",
      category: { zh: "通信 / CODESYS", en: "Communication / CODESYS" },
      series: { zh: "MQTT Client", en: "MQTT Client" },
      progress: { zh: "第1篇/共12篇", en: "Part 1 / 12" },
      status: { zh: "01 / MQTT Client", en: "01 / MQTT Client" },
      keywords: "MQTT Client CODESYS 开源 NBS TCP PLC 协议分层 IEC ST",
    },
    {
      id: "codesys-mqtt-series",
      type: { zh: "文章", en: "Article" },
      title: { zh: "MQTT 系列专题", en: "MQTT Series Topic" },
      copy: {
        zh: "已发布服务器、客户端、Broker、主题通信和排障教程，先跳转 CSDN 分类页。",
        en: "Published tutorials cover server, client, broker, topic communication, and troubleshooting. Link to the CSDN category first.",
      },
      href: "https://blog.csdn.net/weixin_44442562/category_13163069.html",
      searchHref: "#articles",
      category: { zh: "通信 / CODESYS", en: "Communication / CODESYS" },
      series: { zh: "MQTT", en: "MQTT" },
      status: { zh: "外部分发 / CSDN", en: "External / CSDN" },
      keywords: "CODESYS MQTT broker server client topic CSDN tutorial",
    },
  ],
  products: [
    {
      id: "syncbridge",
      type: { zh: "产品", en: "Product" },
      title: { zh: "SyncBridge", en: "SyncBridge" },
      copy: {
        zh: "把 CodeSys / SmartControl IDE 中受支持的工程对象导出为 Git 和 AI 可读的 ST / XML 文件，通过 Compare 审查真实差异，再由工程师受控写回。",
        en: "Exports supported CodeSys / SmartControl IDE objects into readable ST / XML files, reviews meaningful changes through Compare, and writes approved updates back under explicit engineer control.",
      },
      href: "#products-syncbridge",
      cover: "assets/images/products/syncbridge-cover.png",
      version: "V1.4",
      category: { zh: "CodeSys 工程 AI 同步工具", en: "AI-ready project synchronization for CodeSys" },
      headline: {
        zh: "让 AI 看懂工程，让工程师掌握写回。",
        en: "Make the project readable to AI. Keep write-back under engineering control.",
      },
      cardPills: { zh: ["V1.4", "工程同步", "差异审查"], en: ["V1.4", "Project sync", "Diff review"] },
      status: { zh: "正式发布", en: "Released" },
      access: { zh: "官网唯一渠道", en: "Official website only" },
      pain: {
        zh: "解决痛点：IDE 工程对象不适合直接交给 Git 和 AI 阅读；复制粘贴又难以稳定保留对象路径、修改基线和写回方向。",
        en: "Pain solved: IDE project objects are not directly readable by Git and AI, while copy-and-paste loses stable object paths, baselines, and write-back direction.",
      },
      capabilities: {
        zh: ["受支持工程对象导出为可读 ST / XML 文件", "过滤格式噪声并展示真实差异", "工作区、版本和 ST 结构预检后受控写回"],
        en: ["Readable ST / XML export for supported objects", "Meaningful diff review without transport noise", "Controlled write-back after workspace, version, and ST structure checks"],
      },
      capabilityDetails: {
        zh: [
          { title: "工程可读", copy: "把受支持的 IDE 对象导出为稳定文件结构，便于 Git 版本管理和 AI 阅读。" },
          { title: "差异可见", copy: "过滤 BOM、换行等格式噪声，集中展示真实内容差异、单边对象和移动关系。" },
          { title: "写回可控", copy: "工作区、版本和 ST 结构预检通过后，最终写回方向仍由工程师明确确认。" },
        ],
        en: [
          { title: "Readable projects", copy: "Export supported IDE objects into stable files for Git review and AI collaboration." },
          { title: "Visible differences", copy: "Filter BOM and line-ending noise to focus on content changes, one-sided objects, and moves." },
          { title: "Controlled write-back", copy: "Require workspace, version, and ST structure checks before an engineer confirms the write-back direction." },
        ],
      },
      cardCapabilities: {
        zh: ["工程可读", "差异可见", "写回可控"],
        en: ["Readable projects", "Visible differences", "Controlled write-back"],
      },
      workflow: {
        zh: ["SetDir 绑定同步目录", "Export 建立工程基线", "AI / Git 审查或修改", "Compare 确认真实差异", "Import 写回已确认对象", "保存工程并 Build"],
        en: ["Bind the workspace with SetDir", "Establish a baseline with Export", "Review or edit with AI / Git", "Confirm meaningful changes with Compare", "Import approved objects", "Save and Build"],
      },
      workflowSteps: {
        zh: [
          { title: "SetDir", copy: "绑定当前工程的同步目录。" },
          { title: "Export", copy: "导出受支持对象，建立可读基线。" },
          { title: "AI / Git", copy: "审查或修改磁盘中的 ST / XML 文件。" },
          { title: "Compare", copy: "确认真实差异和写入方向。" },
          { title: "Import", copy: "只写回已经确认的对象。" },
          { title: "Save & Build", copy: "保存、构建，并按项目要求继续验证。" },
        ],
        en: [
          { title: "SetDir", copy: "Bind the synchronization workspace for the current project." },
          { title: "Export", copy: "Export supported objects and establish a readable baseline." },
          { title: "AI / Git", copy: "Review or edit the ST / XML files on disk." },
          { title: "Compare", copy: "Confirm meaningful differences and the write direction." },
          { title: "Import", copy: "Write back only the objects that have been approved." },
          { title: "Save & Build", copy: "Save, build, and continue project-specific validation." },
        ],
      },
      facts: {
        zh: [
          { label: "授权", value: "单台设备" },
          { label: "价格", value: "149 元/台" },
          { label: "升级", value: "V1.x 免费" },
          { label: "重大版本", value: "V2.0 付费" },
        ],
        en: [
          { label: "License", value: "Single device" },
          { label: "Price", value: "CNY 149 / device" },
          { label: "Updates", value: "V1.x included" },
          { label: "Major version", value: "V2.0 paid" },
        ],
      },
      compatibility: {
        zh: {
          title: "升级，不切断已有工程上下文。",
          copy: "可识别的旧同步目录可以原地继续使用。SyncBridge 补写当前工作区身份，但不移动或删除已有旁路资料。",
          items: ["docs/ 保留", ".git/ 保留", "AI 会话资料保留", "非同步文件保留"],
        },
        en: {
          title: "Upgrade without breaking existing project context.",
          copy: "Recognizable legacy workspaces remain usable in place. SyncBridge records the current workspace identity without moving or deleting sidecar material.",
          items: ["Keep docs/", "Keep .git/", "Keep AI session material", "Keep non-sync files"],
        },
      },
      boundaries: {
        zh: [
          { label: "SyncBridge 负责", value: "Export、Compare、结构预检和受控 Import" },
          { label: "SyncBridge 不负责", value: "后台自动覆盖、自动创建工程、替代工程师判断" },
          { label: "工程师负责", value: "审查方向、保存工程、Build、仿真和真机验证" },
          { label: "对象支持范围", value: "以产品实际识别结果为准，不承诺全部硬件节点和设备 XML" },
        ],
        en: [
          { label: "SyncBridge handles", value: "Export, Compare, structure checks, and controlled Import" },
          { label: "SyncBridge does not", value: "Overwrite in the background, create projects automatically, or replace engineering judgment" },
          { label: "Engineers handle", value: "Direction review, project save, Build, simulation, and on-machine validation" },
          { label: "Object support", value: "Follows actual product detection; not every hardware node or device XML is guaranteed" },
        ],
      },
      purchase: {
        zh: { label: "商业授权 · V1.4", price: "149 元/台", policy: "V1.x 免费升级，V2.0 付费升级。", cta: "通过官网联系购买", channel: "唯一购买、激活申请和支持渠道" },
        en: { label: "Commercial license · V1.4", price: "CNY 149 / device", policy: "V1.x updates included; V2.0 is a paid upgrade.", cta: "Contact through the website", channel: "The only channel for purchase, activation requests, and support" },
      },
      faq: {
        zh: [
          { question: "使用时必须一直联网吗？", answer: "首次激活和周期性授权复核需要联网；正常工程操作不是每次都要求实时联网。" },
          { question: "AI 写的 ST 一定能编译吗？", answer: "不能保证。同步协议预检不替代业务逻辑审查、Build、仿真和真机验证。" },
          { question: "旧同步目录需要重建吗？", answer: "不需要。保留可识别旧元数据时，目录会原地兼容，旁路文档和 Git 数据保持不动。" },
        ],
        en: [
          { question: "Must SyncBridge stay online?", answer: "Initial activation and periodic license review require connectivity; ordinary engineering actions do not require a live connection every time." },
          { question: "Will AI-written ST always compile?", answer: "No. Protocol prechecks do not replace logic review, Build, simulation, or on-machine validation." },
          { question: "Must a legacy workspace be rebuilt?", answer: "No. When recognizable legacy metadata remains, the workspace is adopted in place while sidecar documents and Git data stay untouched." },
        ],
      },
      delivery: {
        zh: "149 元/台，V1.x 免费升级，V2.0 付费升级。购买、激活申请和支持只通过 ControlRookie 官网。SyncBridge 不自动创建工程或替代 Build、仿真和真机验证。",
        en: "CNY 149 per device. V1.x updates are included; V2.0 is a paid upgrade. Purchase, activation requests, and support are handled only through the ControlRookie website. SyncBridge does not create projects automatically or replace Build, simulation, and on-machine validation.",
      },
      aliases: "SyncBridge 同步桥 工程同步器 AI ST 差异审查 写回",
      keywords: "SyncBridge CodeSys SmartControl AI ST XML Export Compare Import project sync 同步器",
    },
  ],
  contacts: [
    {
      id: "wechat-peaceandbless",
      type: { zh: "联系", en: "Contact" },
      title: { zh: "微信 PeaceAndBless", en: "WeChat PeaceAndBless" },
      copy: { zh: "个人微信二维码", en: "Personal WeChat QR code" },
      href: "#contact",
      keywords: "WeChat PeaceAndBless 微信",
    },
    {
      id: "email",
      type: { zh: "联系", en: "Contact" },
      title: { zh: "邮箱 ben_peng0205@hotmail.com", en: "Email ben_peng0205@hotmail.com" },
      copy: { zh: "合作咨询、工具试用和工程效率交流", en: "Collaboration, tool trials, and engineering efficiency discussions" },
      href: "mailto:ben_peng0205@hotmail.com",
      keywords: "email mail contact cooperation",
    },
    {
      id: "official-account",
      type: { zh: "联系", en: "Contact" },
      title: { zh: "微信公众号 ControlRookie", en: "Official Account ControlRookie" },
      copy: { zh: "微信公众号二维码", en: "Official account QR code" },
      href: "#contact",
      keywords: "WeChat official account ControlRookie 公众号",
    },
    {
      id: "csdn-blog",
      type: { zh: "文章", en: "Article" },
      title: { zh: "CSDN 技术博客", en: "CSDN Blog" },
      copy: { zh: "ControlRookie 技术博客和工程复盘", en: "ControlRookie technical blog and engineering reviews" },
      href: "https://blog.csdn.net/weixin_44442562?type=blog",
      keywords: "CSDN blog article engineering review",
    },
  ],
};
