// 全站内容数据源：资源、文章、产品和联系方式统一从这里维护。
// 后续新增卡片时，先更新本文件，再让页面渲染和搜索索引复用同一份数据。
window.CONTROLROOKIE_SITE_DATA = {
  resources: [
    {
      id: "source-code",
      type: { zh: "01 · 源代码", en: "01 · Source" },
      title: { zh: "CODESYS 示例工程", en: "CODESYS Examples" },
      copy: {
        zh: "控制逻辑、通信、状态机和工程模板源码。",
        en: "Control logic, communication, state machines, and project templates.",
      },
      status: { zh: "分批整理", en: "Curating" },
      access: { zh: "后续受控下载", en: "Controlled download later" },
      format: { zh: "工程包 / ST / 说明", en: "Project package / ST / notes" },
      detail: {
        zh: "适合想直接看工程结构、状态机、通信封装和模板写法的自动化工程师。当前先作为资源目录入口，真实源码包后续按受控下载和客户转化流程开放。",
        en: "For automation engineers who want project structure, state machines, communication wrappers, and template code. Real packages will later be delivered through controlled download flows.",
      },
      bullets: {
        zh: ["CodeSys 兼容 IDE 工程结构", "状态机与通信逻辑示例", "后续与 MQTT 源码文章互链"],
        en: ["CodeSys-compatible IDE project structure", "State machine and communication logic examples", "Future cross-links with MQTT source articles"],
      },
      related: [{ zh: "查看 MQTT 文章系列", en: "Open MQTT article series", href: "#articles-mqtt" }],
      aliases: "源码 示例工程 ST 工程包 下载",
      keywords: "PLC CODESYS source code example project control logic state machine ST engineering package download",
      href: "#works-source-code",
    },
    {
      id: "plc-library",
      type: { zh: "02 · 库文件", en: "02 · Library" },
      title: { zh: "PLC Library", en: "PLC Library" },
      copy: {
        zh: "可复用功能块、通信封装和工程基础库。",
        en: "Reusable function blocks, communication wrappers, and base libraries.",
      },
      status: { zh: "规划中", en: "Planned" },
      access: { zh: "按版本开放", en: "Versioned access" },
      format: { zh: "库文件 / 功能块", en: "Library / function blocks" },
      detail: {
        zh: "用于沉淀可复用功能块、通信封装和工程基础库。后续会按版本、适用平台和依赖关系拆分，避免把库文件变成一堆不可维护的压缩包。",
        en: "Reusable function blocks, communication wrappers, and base libraries. Future releases will be organized by version, platform, and dependency boundaries.",
      },
      bullets: {
        zh: ["功能块边界和调用约定", "通信封装与基础工具", "版本、平台和依赖说明"],
        en: ["Function block boundaries and call contracts", "Communication wrappers and base tools", "Version, platform, and dependency notes"],
      },
      related: [{ zh: "联系获取试用范围", en: "Discuss trial scope", href: "#contact" }],
      aliases: "库 功能块 FB library",
      keywords: "PLC library function block communication wrapper FB",
      href: "#works-plc-library",
    },
    {
      id: "engineering-standards",
      type: { zh: "03 · 标准", en: "03 · Standard" },
      title: { zh: "工程标准", en: "Engineering Standards" },
      copy: {
        zh: "命名、状态机、交付、测试和文档规范。",
        en: "Naming, state machines, delivery, testing, and documentation rules.",
      },
      status: { zh: "持续沉淀", en: "Ongoing" },
      access: { zh: "部分公开", en: "Partly public" },
      format: { zh: "规范 / 清单 / 模板", en: "Standards / checklists / templates" },
      detail: {
        zh: "覆盖命名、状态机、交付、测试和文档规范。目标不是写漂亮制度，而是让团队交付时少靠记忆和口头提醒。",
        en: "Naming, state machines, delivery, testing, and documentation standards. The goal is fewer memory-based and verbal-only engineering practices.",
      },
      bullets: {
        zh: ["命名与目录约定", "交付和测试清单", "文档模板与评审规则"],
        en: ["Naming and folder conventions", "Delivery and test checklists", "Documentation templates and review rules"],
      },
      related: [{ zh: "查看工程效率产品", en: "Open engineering tool", href: "#products-syncbridge" }],
      aliases: "规范 标准 checklist 交付 测试",
      keywords: "standard naming state machine test documentation checklist delivery",
      href: "#works-engineering-standards",
    },
    {
      id: "project-scaffold",
      type: { zh: "04 · 模板", en: "04 · Template" },
      title: { zh: "项目脚手架", en: "Project Scaffold" },
      copy: {
        zh: "工程初始化、目录结构、清单和验证流程。",
        en: "Initialization, folder structure, checklists, and validation workflows.",
      },
      status: { zh: "设计中", en: "Designing" },
      access: { zh: "后续开放", en: "Later release" },
      format: { zh: "目录结构 / 清单 / 脚本", en: "Folders / checklists / scripts" },
      detail: {
        zh: "把工程初始化、目录结构、清单和验证流程前置，减少每个项目从空白目录开始造轮子的时间。",
        en: "Moves initialization, folder structure, checklists, and validation forward so projects do not start from an empty directory each time.",
      },
      bullets: {
        zh: ["工程目录和命名骨架", "发布前检查清单", "静态验证和生成脚本入口"],
        en: ["Project folder and naming skeleton", "Pre-release checklist", "Static validation and generation scripts"],
      },
      related: [{ zh: "联系讨论适用项目", en: "Discuss project fit", href: "#contact" }],
      aliases: "脚手架 模板 scaffold 初始化",
      keywords: "template scaffold checklist validation workflow initialization",
      href: "#works-project-scaffold",
    },
    {
      id: "mqtt-resources",
      type: { zh: "05 · 协议", en: "05 · Protocol" },
      title: { zh: "MQTT 资料", en: "MQTT Resources" },
      copy: {
        zh: "服务器、客户端、主题设计和排障资料。",
        en: "Server, client, topic design, and troubleshooting references.",
      },
      status: { zh: "已关联文章", en: "Linked articles" },
      access: { zh: "文章优先公开", en: "Articles first" },
      format: { zh: "教程 / 图 / 源码说明", en: "Tutorials / diagrams / source notes" },
      detail: {
        zh: "围绕 MQTT Client、Broker、主题设计和排障资料展开。当前官网已经发布 MQTT Client 与 Broker 双系列文章，资料入口优先和文章互链。",
        en: "Covers MQTT Client, Broker, topic design, and troubleshooting. The website already publishes both Client and Broker article series.",
      },
      bullets: {
        zh: ["Client 与 Broker 双系列", "主题、QoS、KeepAlive 和 Retain", "现场排障与源码说明"],
        en: ["Client and Broker series", "Topic, QoS, KeepAlive, and Retain", "Troubleshooting and source notes"],
      },
      related: [{ zh: "进入 CodeSys MQTT 系列", en: "Open CodeSys MQTT series", href: "#articles-mqtt" }],
      aliases: "MQTT Client Broker 协议 通信",
      keywords: "MQTT broker server client topic troubleshooting protocol communication",
      href: "#works-mqtt-resources",
    },
    {
      id: "automation-scripts",
      type: { zh: "06 · 脚本", en: "06 · Script" },
      title: { zh: "自动化脚本", en: "Automation Scripts" },
      copy: {
        zh: "面向工程效率的批处理、检查和生成工具。",
        en: "Batch, checking, and generation tools for engineering efficiency.",
      },
      status: { zh: "内部使用中", en: "Internal use" },
      access: { zh: "择机开放", en: "Selective release" },
      format: { zh: "脚本 / 检查器 / 生成器", en: "Scripts / checkers / generators" },
      detail: {
        zh: "面向工程效率的批处理、检查和生成工具。后续只开放能稳定复用、不会误伤工程文件的脚本。",
        en: "Batch, checking, and generation tools for engineering efficiency. Future releases will prioritize stable tools that do not risk project files.",
      },
      bullets: {
        zh: ["批处理和格式检查", "文章/资源生成辅助", "工程发布前自动检查"],
        en: ["Batch processing and formatting checks", "Article/resource generation helpers", "Pre-release project checks"],
      },
      related: [{ zh: "查看技术文章", en: "Open articles", href: "#articles" }],
      aliases: "脚本 自动化 批处理 检查 生成",
      keywords: "automation scripts batch check generator engineering efficiency",
      href: "#works-automation-scripts",
    },
    {
      id: "llm-workflows",
      type: { zh: "07 · AI", en: "07 · AI" },
      title: { zh: "LLM 工作流", en: "LLM Workflows" },
      copy: {
        zh: "提示词、技能、Agent 和自动化协作规则。",
        en: "Prompts, skills, agents, and automation collaboration rules.",
      },
      status: { zh: "持续迭代", en: "Iterating" },
      access: { zh: "按场景开放", en: "Scenario-based" },
      format: { zh: "提示词 / 技能 / Agent 规则", en: "Prompts / skills / agent rules" },
      detail: {
        zh: "沉淀提示词、技能、Agent 和自动化协作规则。重点不是炫技，而是让 AI 真正接得住控制工程项目上下文。",
        en: "Prompts, skills, agents, and automation collaboration rules. The focus is making AI handle control-engineering context instead of showing tricks.",
      },
      bullets: {
        zh: ["项目规则和上下文同步", "技能与 Agent 协作方式", "AI 工程效率工作流"],
        en: ["Project rules and context sync", "Skill and agent collaboration", "AI engineering efficiency workflow"],
      },
      related: [{ zh: "查看工程效率产品", en: "Open engineering tool", href: "#products-syncbridge" }],
      aliases: "AI LLM Agent 提示词 工作流 同步器",
      keywords: "LLM prompt skill agent workflow AI automation synchronizer",
      href: "#works-llm-workflows",
    },
    {
      id: "engineering-library",
      type: { zh: "08 · 资料", en: "08 · Reference" },
      title: { zh: "工程资料库", en: "Engineering Library" },
      copy: {
        zh: "手册、笔记、复盘和关键技术路线图。",
        en: "Manuals, notes, reviews, and technical roadmaps.",
      },
      status: { zh: "整理中", en: "Curating" },
      access: { zh: "后续分级开放", en: "Tiered access later" },
      format: { zh: "手册 / 笔记 / 复盘", en: "Manuals / notes / reviews" },
      detail: {
        zh: "手册、笔记、复盘和关键技术路线图的长期入口。资料会按公开、留资、客户授权和付费等条件分级开放。",
        en: "Long-term entry for manuals, notes, reviews, and technical roadmaps. Access will be tiered by public, lead, customer, and paid conditions.",
      },
      bullets: {
        zh: ["工程手册和关键笔记", "项目复盘和路线图", "后续受控下载系统承接"],
        en: ["Engineering manuals and key notes", "Project reviews and roadmaps", "Future controlled-download delivery"],
      },
      related: [{ zh: "联系获取资料范围", en: "Discuss reference scope", href: "#contact" }],
      aliases: "资料 手册 笔记 复盘 roadmap",
      keywords: "manual note review roadmap engineering reference controlled download",
      href: "#works-engineering-library",
    },
  ],
  articles: window.CONTROLROOKIE_ARTICLES || [
    {
      id: "mqtt-client-open-source-codesys-layer",
      type: { zh: "文章", en: "Article" },
      title: {
        zh: "官方 MQTT 库要花钱？我为什么自己开源了一套 CODESYS MQTT 客户端",
        en: "Why I Built an Open Source CODESYS MQTT Client",
      },
      copy: {
        zh: "MQTT Client 系列第一篇：为什么要做开源客户端、MQTT 在哪一层、以及 NBS TCP 与 MQTT 的工程关系。",
        en: "The first MQTT Client article: why this open source client exists, where MQTT sits, and how NBS TCP carries MQTT in CODESYS.",
      },
      href: "articles/mqtt-client-open-source-codesys-layer/index.html",
      category: { zh: "通信 / CODESYS", en: "Communication / CODESYS" },
      series: { zh: "MQTT Client", en: "MQTT Client" },
      progress: { zh: "第1篇/共12篇", en: "Part 1 / 12" },
      status: { zh: "01 / MQTT Client", en: "01 / MQTT Client" },
      keywords: "MQTT Client CODESYS 开源 NBS TCP PLC 协议分层 IEC ST",
    },
    {
      id: "codesys-mqtt-series",
      type: { zh: "文章", en: "Article" },
      title: { zh: "MQTT 系列专题", en: "MQTT Series Topic" },
      copy: {
        zh: "已发布服务器、客户端、Broker、主题通信和排障教程，先跳转 CSDN 分类页。",
        en: "Published tutorials cover server, client, broker, topic communication, and troubleshooting. Link to the CSDN category first.",
      },
      href: "https://blog.csdn.net/weixin_44442562/category_13163069.html",
      searchHref: "#articles",
      category: { zh: "通信 / CODESYS", en: "Communication / CODESYS" },
      series: { zh: "MQTT", en: "MQTT" },
      status: { zh: "外部分发 / CSDN", en: "External / CSDN" },
      keywords: "CODESYS MQTT broker server client topic CSDN tutorial",
    },
  ],
  products: [
    {
      id: "syncbridge",
      type: { zh: "产品", en: "Product" },
      title: { zh: "SyncBridge", en: "SyncBridge" },
      copy: {
        zh: "把 CodeSys 兼容 IDE 中受支持的工程对象导出为 Git 和 AI 可读文件，通过 Compare 逐对象、逐行审查真实差异，再由工程师确认后写回。",
        en: "Exports supported objects from CodeSys-compatible IDEs into files readable by Git and AI, reviews object and line-level differences through Compare, and writes approved updates back under engineer control.",
      },
      href: "#products-syncbridge",
      cover: "assets/images/products/syncbridge-cover.png",
      version: "V1.4.1",
      category: { zh: "CodeSys 内置式 AI 同步工具", en: "In-IDE AI synchronization for CodeSys" },
      headline: {
        zh: "打通 CODESYS 工程与 AI 协作的双向通道",
        en: "A bidirectional engineering bridge between CODESYS and AI",
      },
      positioning: {
        zh: "面向自动化工程师的 CODESYS 内置式 AI 同步工具。",
        en: "An in-IDE AI synchronization tool for CODESYS automation engineers.",
      },
      cardPills: { zh: ["V1.4.1", "工程同步", "差异审查"], en: ["V1.4.1", "Project sync", "Diff review"] },
      status: { zh: "正式发布", en: "Released" },
      access: { zh: "官网唯一渠道", en: "Official website only" },
      pain: {
        zh: "解决痛点：IDE 工程对象不适合直接交给 Git 和 AI 阅读；复制粘贴又难以稳定保留对象路径、修改基线和写回方向。",
        en: "Pain solved: IDE project objects are not directly readable by Git and AI, while copy-and-paste loses stable object paths, baselines, and write-back direction.",
      },
      capabilities: {
        zh: ["受支持工程对象导出为可读 ST / XML 文件", "过滤格式噪声并展示真实差异", "工作区、版本和 ST 结构预检后受控写回"],
        en: ["Readable ST / XML export for supported objects", "Meaningful diff review without transport noise", "Controlled write-back after workspace, version, and ST structure checks"],
      },
      capabilityDetails: {
        zh: [
          { title: "工程可读", copy: "把受支持的 IDE 对象导出为稳定文件结构，便于 Git 版本管理和 AI 阅读。" },
          { title: "差异可见", copy: "过滤 BOM、换行等格式噪声，集中展示真实内容差异、单边对象和移动关系。" },
          { title: "写回可控", copy: "工作区、版本和 ST 结构预检通过后，最终写回方向仍由工程师明确确认。" },
        ],
        en: [
          { title: "Readable projects", copy: "Export supported IDE objects into stable files for Git review and AI collaboration." },
          { title: "Visible differences", copy: "Filter BOM and line-ending noise to focus on content changes, one-sided objects, and moves." },
          { title: "Controlled write-back", copy: "Require workspace, version, and ST structure checks before an engineer confirms the write-back direction." },
        ],
      },
      cardCapabilities: {
        zh: ["工程可读", "差异可见", "写回可控"],
        en: ["Readable projects", "Visible differences", "Controlled write-back"],
      },
      primaryVisual: {
        src: "assets/images/products/syncbridge-compare-hero.png",
        alt: {
          zh: "SyncBridge 在 CODESYS 兼容 IDE 中提供六个工具栏命令、Compare 对象选择和逐行代码差异审查",
          en: "SyncBridge toolbar commands, Compare object selection, and line-level code review inside a CODESYS-compatible IDE",
        },
        caption: {
          zh: "Compare：从工程对象到逐行代码，先看清差异，再决定写入方向。",
          en: "Compare: inspect object and line-level changes before choosing the write direction.",
        },
      },
      coreFlow: {
        zh: [
          { title: "Export", kicker: "工程可读化", copy: "把受支持的工程对象导出为 AI 与 Git 可读文件。" },
          { title: "Compare", kicker: "差异审查", copy: "逐对象、逐行确认真实变化，并明确导入或导出方向。" },
          { title: "Import", kicker: "受控写回", copy: "只把工程师确认过的对象安全写回 IDE。" },
        ],
        en: [
          { title: "Export", kicker: "Readable engineering", copy: "Export supported project objects into files readable by AI and Git." },
          { title: "Compare", kicker: "Diff review", copy: "Inspect real object and line-level changes, then choose the direction." },
          { title: "Import", kicker: "Controlled write-back", copy: "Write only engineer-approved objects back to the IDE." },
        ],
      },
      supportCommands: {
        zh: [
          { title: "Set Dir", copy: "绑定当前工程的同步目录。" },
          { title: "Config", copy: "按需同步非 ST 对象。" },
          { title: "AI Report", copy: "生成 AI 可读的编译诊断。" },
        ],
        en: [
          { title: "Set Dir", copy: "Bind the current project workspace." },
          { title: "Config", copy: "Optionally include non-ST objects." },
          { title: "AI Report", copy: "Generate AI-readable compiler diagnostics." },
        ],
      },
      painPoints: {
        zh: [
          { title: "手动同步", copy: "复制粘贴效率低，工程对象多时容易漏改和误改。" },
          { title: "差异不清", copy: "代码量大时，很难准确判断 AI 修改了哪些内容。" },
          { title: "版本混乱", copy: "多轮修改后，IDE 与磁盘谁是最新版难以确认。" },
          { title: "连通壁垒", copy: "普通自动化工程师难以稳定打通 IDE 与 AI 工作流。" },
          { title: "方案门槛", copy: "复杂平台部署和高昂价格阻碍日常工程使用。" },
        ],
        en: [
          { title: "Manual sync", copy: "Copy-and-paste is slow and error-prone in projects with many objects." },
          { title: "Invisible changes", copy: "Large codebases make it difficult to identify exactly what AI changed." },
          { title: "Version confusion", copy: "After multiple edits, the newest source between IDE and disk becomes unclear." },
          { title: "Connectivity barrier", copy: "Most engineers cannot reliably connect the IDE to an AI workflow." },
          { title: "High adoption cost", copy: "Complex deployment and expensive solutions block everyday use." },
        ],
      },
      advantages: {
        zh: [
          { title: "IDE 内置", copy: "六个工具栏按钮直接进入日常工程流程。" },
          { title: "双向打通", copy: "工程可导出给 AI，也可将确认结果写回 IDE。" },
          { title: "工程可读", copy: "工程对象转换为结构清晰的 ST / XML 文件。" },
          { title: "差异可见", copy: "逐对象、逐行查看真正发生的变化。" },
          { title: "结构一致", copy: "磁盘源码保持工程树结构和对象关系。" },
          { title: "写回可控", copy: "导入对象和写入方向由工程师最终确认。" },
          { title: "轻量小巧", copy: "无需部署复杂平台、服务或数据库。" },
          { title: "性能优秀", copy: "面向包含大量对象的复杂工程持续优化。" },
        ],
        en: [
          { title: "In-IDE", copy: "Six toolbar commands fit directly into daily engineering work." },
          { title: "Bidirectional", copy: "Export projects to AI and write approved results back to the IDE." },
          { title: "Readable", copy: "Convert project objects into structured ST / XML files." },
          { title: "Visible diffs", copy: "Inspect meaningful changes by object and by line." },
          { title: "Structure preserved", copy: "Keep project-tree structure and object relationships on disk." },
          { title: "Controlled write-back", copy: "Engineers make the final object and direction decisions." },
          { title: "Lightweight", copy: "No complex platform, service, or database deployment." },
          { title: "Optimized", copy: "Continuously optimized for complex projects with many objects." },
        ],
      },
      comparison: {
        zh: [
          { before: "手动复制粘贴", after: "一键导出工程对象" },
          { before: "靠人工寻找修改", after: "自动识别真实差异" },
          { before: "容易覆盖错误版本", after: "明确 IDE / 磁盘写入方向" },
          { before: "AI 只能看到零散代码", after: "AI 获得完整工程结构" },
          { before: "大工程逐项处理", after: "对象级批量审查与同步" },
        ],
        en: [
          { before: "Manual copy-and-paste", after: "One-click project-object export" },
          { before: "Find edits manually", after: "Detect meaningful differences automatically" },
          { before: "Overwrite the wrong version", after: "Choose the IDE / disk direction explicitly" },
          { before: "AI sees isolated snippets", after: "AI receives complete project structure" },
          { before: "Handle large projects item by item", after: "Review and sync objects in batches" },
        ],
      },
      aiValues: {
        zh: [
          { title: "复杂程序开发", copy: "辅助算法、通信协议和面向对象程序设计。" },
          { title: "经验资产沉淀", copy: "把功能块、库、工艺代码和参数配方产品化。" },
          { title: "企业标准落地", copy: "构建标准框架、编程助手和行业工艺助手。" },
          { title: "大型旧工程解析", copy: "梳理无注释、逻辑复杂的大规模历史工程。" },
        ],
        en: [
          { title: "Complex program development", copy: "Assist algorithms, protocols, and object-oriented programming." },
          { title: "Engineering knowledge assets", copy: "Productize function blocks, libraries, process code, and recipes." },
          { title: "Enterprise standards", copy: "Build standard frameworks, coding assistants, and industry copilots." },
          { title: "Legacy project analysis", copy: "Understand large historical projects with sparse documentation." },
        ],
      },
      featureDetails: {
        zh: [
          { title: "Set Dir", copy: "绑定当前工程的同步目录，只建立关系，不导入、不导出、不覆盖。" },
          { title: "Export", copy: "全量导出受支持对象，建立 AI 与 Git 可读取的工程基线。" },
          { title: "Import", copy: "分析磁盘变更，只把工程师确认过的对象写回 IDE。" },
          { title: "Compare", copy: "逐对象、逐行对比真实差异；比较本身不写入任何一侧。" },
          { title: "Config", copy: "按需同步可视化、报警等非 ST 对象的 XML 文件，默认关闭。" },
          { title: "AI Report", copy: "调用 IDE 编译并生成 AI 可读取的错误、警告和位置报告。" },
        ],
        en: [
          { title: "Set Dir", copy: "Bind the current project workspace without importing, exporting, or overwriting content." },
          { title: "Export", copy: "Export supported objects and establish a project baseline readable by AI and Git." },
          { title: "Import", copy: "Analyze disk changes and write back only objects approved by the engineer." },
          { title: "Compare", copy: "Review object and line-level differences without writing to either side." },
          { title: "Config", copy: "Optionally synchronize XML for visualization, alarm, and other non-ST objects; off by default." },
          { title: "AI Report", copy: "Run the IDE compiler and generate an AI-readable error, warning, and location report." },
        ],
      },
      visualEvidence: {
        zh: [
          { src: "assets/images/products/syncbridge-real-diff.png", alt: "SyncBridge 真实代码差异窗口", title: "逐行审查 IDE 与磁盘差异" },
          { src: "assets/images/products/syncbridge-real-compare.png", alt: "SyncBridge 真实 Compare 主窗口", title: "按对象确认差异和写入方向" },
          { src: "assets/images/products/syncbridge-real-progress.png", alt: "SyncBridge 真实处理进度窗口", title: "持续反馈当前处理状态" },
        ],
        en: [
          { src: "assets/images/products/syncbridge-real-diff.png", alt: "Real SyncBridge code-diff window", title: "Review IDE and disk changes line by line" },
          { src: "assets/images/products/syncbridge-real-compare.png", alt: "Real SyncBridge Compare window", title: "Confirm objects and write direction" },
          { src: "assets/images/products/syncbridge-real-progress.png", alt: "Real SyncBridge progress window", title: "Track current processing status" },
        ],
      },
      workflow: {
        zh: ["Set Dir 绑定同步目录", "Export 建立工程基线", "AI / Git 审查或修改", "Compare 确认真实差异", "Import 写回已确认对象", "保存、AI Report、再次 Compare"],
        en: ["Bind the workspace with Set Dir", "Establish a baseline with Export", "Review or edit with AI / Git", "Confirm meaningful changes with Compare", "Import approved objects", "Save, run AI Report, and Compare again"],
      },
      workflowSteps: {
        zh: [
          { title: "Set Dir", copy: "默认指向当前工程所在目录，也可选择其他同步目录。" },
          { title: "Export", copy: "导出受支持对象，建立可读基线。" },
          { title: "AI / Git", copy: "审查或修改磁盘中的 ST / XML 文件。" },
          { title: "Compare", copy: "确认真实差异和写入方向。" },
          { title: "Import", copy: "只写回已经确认的对象。" },
          { title: "保存与复核", copy: "保存工程，运行 AI Report，再次 Compare，并继续仿真或真机验证。" },
        ],
        en: [
          { title: "Set Dir", copy: "Use the current project directory by default or select another workspace." },
          { title: "Export", copy: "Export supported objects and establish a readable baseline." },
          { title: "AI / Git", copy: "Review or edit the ST / XML files on disk." },
          { title: "Compare", copy: "Confirm meaningful differences and the write direction." },
          { title: "Import", copy: "Write back only the objects that have been approved." },
          { title: "Save and verify", copy: "Save the project, run AI Report, Compare again, and continue simulation or on-machine validation." },
        ],
      },
      facts: {
        zh: [
          { label: "授权", value: "单台设备" },
          { label: "获取方式", value: "联系开发者报价" },
          { label: "升级", value: "V1.x 免费" },
          { label: "重大版本", value: "V2.0 付费" },
        ],
        en: [
          { label: "License", value: "Single device" },
          { label: "Pricing", value: "Contact the developer" },
          { label: "Updates", value: "V1.x included" },
          { label: "Major version", value: "V2.0 paid" },
        ],
      },
      compatibility: {
        zh: {
          title: "升级，不切断已有工程上下文。",
          copy: "可识别的旧同步目录可以原地继续使用。SyncBridge 补写当前工作区身份，但不移动或删除已有旁路资料。",
          items: ["docs/ 保留", ".git/ 保留", "AI 会话资料保留", "非同步文件保留"],
        },
        en: {
          title: "Upgrade without breaking existing project context.",
          copy: "Recognizable legacy workspaces remain usable in place. SyncBridge records the current workspace identity without moving or deleting sidecar material.",
          items: ["Keep docs/", "Keep .git/", "Keep AI session material", "Keep non-sync files"],
        },
      },
      boundaries: {
        zh: [
          { label: "SyncBridge 负责", value: "Set Dir、Export、Import、Compare、Config 和 AI Report" },
          { label: "SyncBridge 不负责", value: "后台自动覆盖、自动创建工程、替代工程师判断" },
          { label: "工程师负责", value: "审查方向、保存工程、仿真和真机验证" },
          { label: "对象支持范围", value: "以产品实际识别结果为准，不承诺全部硬件节点和设备 XML" },
        ],
        en: [
          { label: "SyncBridge handles", value: "Set Dir, Export, Import, Compare, Config, and AI Report" },
          { label: "SyncBridge does not", value: "Overwrite in the background, create projects automatically, or replace engineering judgment" },
          { label: "Engineers handle", value: "Direction review, project save, simulation, and on-machine validation" },
          { label: "Object support", value: "Follows actual product detection; not every hardware node or device XML is guaranteed" },
        ],
      },
      purchase: {
        zh: { label: "商业授权 · V1.4.1", price: "联系开发者获取报价", policy: "按实际使用场景确认授权方案；V1.x 免费升级，V2.0 付费升级。", cta: "联系开发者", channel: "官网是唯一购买、激活申请和支持渠道" },
        en: { label: "Commercial license · V1.4.1", price: "Contact the developer for pricing", policy: "Licensing is quoted for the actual usage scenario; V1.x updates are included and V2.0 is a paid upgrade.", cta: "Contact the developer", channel: "The official website is the only purchase, activation, and support channel" },
      },
      faq: {
        zh: [
          { question: "使用时必须一直联网吗？", answer: "首次激活和周期性授权复核需要联网；正常工程操作不是每次都要求实时联网。" },
          { question: "AI 写的 ST 一定能编译吗？", answer: "不能保证。AI Report 只记录 IDE 编译诊断，不替代业务逻辑审查、仿真和真机验证。" },
          { question: "旧同步目录需要重建吗？", answer: "不需要。保留可识别旧元数据时，目录会原地兼容，旁路文档和 Git 数据保持不动。" },
        ],
        en: [
          { question: "Must SyncBridge stay online?", answer: "Initial activation and periodic license review require connectivity; ordinary engineering actions do not require a live connection every time." },
          { question: "Will AI-written ST always compile?", answer: "No. AI Report records IDE compiler diagnostics but does not replace logic review, simulation, or on-machine validation." },
          { question: "Must a legacy workspace be rebuilt?", answer: "No. When recognizable legacy metadata remains, the workspace is adopted in place while sidecar documents and Git data stay untouched." },
        ],
      },
      delivery: {
        zh: "联系开发者获取报价；V1.x 免费升级，V2.0 付费升级。购买、激活申请和支持只通过 ControlRookie 官网。",
        en: "Contact the developer for pricing. V1.x updates are included; V2.0 is a paid upgrade. Purchase, activation, and support are available only through the ControlRookie website.",
      },
      aliases: "SyncBridge 同步桥 工程同步器 AI ST 差异审查 写回",
      keywords: "SyncBridge CodeSys compatible IDE AI ST XML Export Compare Import Config AI Report project sync 同步器",
    },
  ],
  contacts: [
    {
      id: "wechat-peaceandbless",
      type: { zh: "联系", en: "Contact" },
      title: { zh: "微信 PeaceAndBless", en: "WeChat PeaceAndBless" },
      copy: { zh: "个人微信二维码", en: "Personal WeChat QR code" },
      href: "#contact",
      keywords: "WeChat PeaceAndBless 微信",
    },
    {
      id: "email",
      type: { zh: "联系", en: "Contact" },
      title: { zh: "邮箱 ben_peng0205@hotmail.com", en: "Email ben_peng0205@hotmail.com" },
      copy: { zh: "合作咨询、工具试用和工程效率交流", en: "Collaboration, tool trials, and engineering efficiency discussions" },
      href: "mailto:ben_peng0205@hotmail.com",
      keywords: "email mail contact cooperation",
    },
    {
      id: "official-account",
      type: { zh: "联系", en: "Contact" },
      title: { zh: "微信公众号 ControlRookie", en: "Official Account ControlRookie" },
      copy: { zh: "微信公众号二维码", en: "Official account QR code" },
      href: "#contact",
      keywords: "WeChat official account ControlRookie 公众号",
    },
    {
      id: "csdn-blog",
      type: { zh: "文章", en: "Article" },
      title: { zh: "CSDN 技术博客", en: "CSDN Blog" },
      copy: { zh: "ControlRookie 技术博客和工程复盘", en: "ControlRookie technical blog and engineering reviews" },
      href: "https://blog.csdn.net/weixin_44442562?type=blog",
      keywords: "CSDN blog article engineering review",
    },
  ],
};
